name: docker-mn

on:
  push:
    branches: [ feature/pres_xml ]
  pull_request:
    branches: [ feature/pres_xml ]
  repository_dispatch:
    types: [ metanorma/metanorma-cli/feature/pres_xml ]

jobs:
  build-debian:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build container
      run: |
        make build-mn

    - name: Run tests
      env:
        GITHUB_CREDENTIALS: "metanorma-ci:${{ secrets.METANORMA_CI_PAT_TOKEN }}"
      run: |
        make test-mn

    - name: Squash and push container
      if: github.ref == 'refs/heads/feature/pres_xml'
      env:
        DOCKER_LOGIN_USERNAME: ${{ secrets.DOCKER_LOGIN_USERNAME }}
        DOCKER_LOGIN_PASSWORD: ${{ secrets.DOCKER_LOGIN_PASSWORD }}
      run: |
        make bsp-mn latest-tp-mn

    - name: Trigger samples repositories
      if: github.ref == 'refs/heads/feature/pres_xml'
      env:
        GH_USERNAME: metanorma-ci
        GH_ACCESS_TOKEN: ${{ secrets.METANORMA_CI_PAT_TOKEN }}
      run: |
        curl -LO --retry 3 https://raw.githubusercontent.com/metanorma/metanorma-build-scripts/master/trigger-gh-actions.sh
        for repo in iso cc gb iec itu ogc un iho nist
        do
          sh trigger-gh-actions.sh $ORGANISATION mn-samples-$repo $GH_USERNAME $GH_ACCESS_TOKEN ${GITHUB_REPOSITORY}/feature/pres_xml
        done

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build container
      run: |
        make build-mn-ubuntu

    - name: Run tests
      env:
        GITHUB_CREDENTIALS: "metanorma-ci:${{ secrets.METANORMA_CI_PAT_TOKEN }}"
      run: |
        make test-mn-ubuntu

    - name: Squash and push container
      if: github.ref == 'refs/heads/feature/pres_xml'
      env:
        DOCKER_LOGIN_USERNAME: ${{ secrets.DOCKER_LOGIN_USERNAME }}
        DOCKER_LOGIN_PASSWORD: ${{ secrets.DOCKER_LOGIN_PASSWORD }}
      run: |
        make bsp-mn-ubuntu latest-tp-mn-ubuntu
